services:

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pnrdb
    volumes:
      - ./docker/mongo/init:/docker-entrypoint-initdb.d
    networks:
      - pnr-net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - pnr-net

  pnr-aggregator:
    build: .
    container_name: pnr-aggregator
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: pnrdb
    networks:
      - pnr-net

networks:
  pnr-net: